package gui.view;

import gui.view.co.CoAutor;

import javax.swing.JDialog;
import javax.swing.JTextField;

public class GUI_principal extends javax.swing.JDialog {
    private CoAutor co_autor;

    /**
     * Creates new form GuiProduto
     */
    public GUI_principal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.co_autor = new CoAutor(this);

        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        tb_autor = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        tb_titulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        tb_ano = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organizador de Livros");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Autor");
        jLabel1.setToolTipText("Informação obrigatória!");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Limpar");
        jButton5.setToolTipText("Limpar os Textos!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tb_autor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tb_autor.setForeground(new java.awt.Color(204, 204, 204));
        tb_autor.setText("(Nome do Autor)");
        tb_autor.setToolTipText("Digite o Nome do Autor!");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Fechar");
        jButton6.setToolTipText("Fechar o Programa!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tb_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tb_titulo.setForeground(new java.awt.Color(204, 204, 204));
        tb_titulo.setText("(Titulo do Livro)");
        tb_titulo.setToolTipText("Digite o Titulo do Livro!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ano");
        jLabel3.setToolTipText("Informação obrigatória!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Título");
        jLabel2.setToolTipText("Informação obrigatória!");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.setToolTipText("Pesquisar um livro!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.setToolTipText("Excluir um livro!");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_salvar.setText("Cadastrar");
        btn_salvar.setToolTipText("Cadastrar um livro!");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        tb_ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tb_ano.setForeground(new java.awt.Color(204, 204, 204));
        tb_ano.setText("(Ano do Livro)");
        tb_ano.setToolTipText("Digite o ano em que o livro foi lançado!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb_autor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(tb_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_ano, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(btn_salvar)
                    .addComponent(btn_excluir)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_excluir)
                        .addGap(9, 9, 9)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(tb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.getCo().limpar();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.getCo().obterLista();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        this.getCo().cadastrar();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        this.getCo().excluir();

    }//GEN-LAST:event_btn_excluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tb_titulo;
    private javax.swing.JTextField tb_ano;
    private javax.swing.JTextField tb_autor;
    // End of variables declaration//GEN-END:variables  

    public CoAutor getCo() {
        return co_autor;
    }


    public void setCo(CoAutor co_autor) {
        this.co_autor = co_autor;
    }

    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public javax.swing.JButton getbtn_salvar() {
        return btn_salvar;
    }

    public void setbtn_salvar(javax.swing.JButton btn_salvar) {
        this.btn_salvar = btn_salvar;
    }

    public javax.swing.JButton getbtn_excluir() {
        return btn_excluir;
    }

    public void setbtn_excluir(javax.swing.JButton btn_excluir) {
        this.btn_excluir = btn_excluir;
    }

    public javax.swing.JButton getjButton5() {
        return jButton5;
    }

    public void setjButton5(javax.swing.JButton jButton5) {
        this.jButton5 = jButton5;
    }

    public javax.swing.JButton getjButton6() {
        return jButton6;
    }

    public void setjButton6(javax.swing.JButton jButton6) {
        this.jButton6 = jButton6;
    }

    public JTextField gettb_ano() {
        return tb_ano;
    }

    public void settb_ano(JTextField tb_ano) {
        this.tb_ano = tb_ano;
    }

    public javax.swing.JTextField gettb_autor() {
        return tb_autor;
    }

    public void setjTextField1(javax.swing.JTextField jTextField1) {
        this.tb_autor = jTextField1;
    }

    public javax.swing.JTextField gettb_titulo() {
        return tb_titulo;
    }

    public void settb_titulo(javax.swing.JTextField tb_titulo) {
        this.tb_titulo = tb_titulo;
    }
}
